import type { CatalogItem } from './types'

export const catalog: CatalogItem[] = [

  // ── DOCUMENTATION & SEARCH ──────────────────────────────────────────────
  {
    name: 'context7',
    title: 'Context7 Docs',
    provider: 'Context7',
    description: 'Up-to-date framework and library documentation. Remote endpoint, no local package required.',
    tags: ['docs', 'remote', 'official'],
    definition: { type: 'remote', url: 'https://mcp.context7.com/mcp', enabled: true },
  },
  {
    name: 'brave-search',
    title: 'Brave Search',
    provider: 'Model Context Protocol',
    description: 'Web and local search via the Brave Search API. Requires a free Brave API key.',
    tags: ['search', 'web', 'official'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@modelcontextprotocol/server-brave-search'],
      environment: { BRAVE_API_KEY: '{env:BRAVE_API_KEY}' },
      enabled: true,
    },
    installNote: 'Get a free key at https://api.search.brave.com',
  },
  {
    name: 'fetch',
    title: 'Fetch',
    provider: 'Model Context Protocol',
    description: 'Fetch any URL and return its content as markdown or raw text. Useful for reading docs on the fly.',
    tags: ['web', 'fetch', 'official'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@modelcontextprotocol/server-fetch'],
      enabled: true,
    },
  },
  {
    name: 'exa-search',
    title: 'Exa Search',
    provider: 'Exa',
    description: 'Neural web search optimised for developers and researchers. Semantic search over the live web.',
    tags: ['search', 'web', 'neural'],
    definition: {
      type: 'local',
      command: ['npx', '-y', 'exa-mcp-server'],
      environment: { EXA_API_KEY: '{env:EXA_API_KEY}' },
      enabled: true,
    },
    installNote: 'Sign up at https://exa.ai to get an API key.',
  },
  {
    name: 'tavily-search',
    title: 'Tavily Search',
    provider: 'Tavily',
    description: 'AI-optimised search engine with deep extraction. Better than raw web for LLM consumption.',
    tags: ['search', 'web', 'ai'],
    definition: {
      type: 'local',
      command: ['npx', '-y', 'tavily-mcp@0.1.4'],
      environment: { TAVILY_API_KEY: '{env:TAVILY_API_KEY}' },
      enabled: true,
    },
  },
  {
    name: 'kagi-search',
    title: 'Kagi Search',
    provider: 'Kagi',
    description: 'Privacy-first search using your Kagi subscription. No tracking, no ads.',
    tags: ['search', 'privacy'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@kagi/mcp-server-kagi'],
      environment: { KAGI_API_KEY: '{env:KAGI_API_KEY}' },
      enabled: true,
    },
  },

  // ── VERSION CONTROL & CODE PLATFORMS ────────────────────────────────────
  {
    name: 'github',
    title: 'GitHub',
    provider: 'Model Context Protocol',
    description: 'GitHub repository, issue, PR and code search operations via a personal access token.',
    tags: ['git', 'github', 'remote-api'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@modelcontextprotocol/server-github'],
      environment: { GITHUB_PERSONAL_ACCESS_TOKEN: '{env:GITHUB_PERSONAL_ACCESS_TOKEN}' },
      enabled: true,
    },
  },
  {
    name: 'gitlab',
    title: 'GitLab',
    provider: 'Community',
    description: 'GitLab projects, merge requests, issues, pipelines and snippets via the GitLab REST API.',
    tags: ['git', 'gitlab', 'remote-api'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@modelcontextprotocol/server-gitlab'],
      environment: {
        GITLAB_PERSONAL_ACCESS_TOKEN: '{env:GITLAB_PERSONAL_ACCESS_TOKEN}',
        GITLAB_API_URL: '{env:GITLAB_API_URL}',
      },
      enabled: true,
    },
  },
  {
    name: 'git',
    title: 'Git',
    provider: 'Model Context Protocol',
    description: 'Local Git repository operations: log, diff, status, blame, and branch management.',
    tags: ['git', 'local', 'official'],
    definition: {
      type: 'local',
      command: ['uvx', 'mcp-server-git', '--repository', '{PROJECT_PATH}'],
      enabled: true,
    },
    installNote: 'Requires Python and uv (https://docs.astral.sh/uv). Replace {PROJECT_PATH} with your repo path.',
  },
  {
    name: 'linear',
    title: 'Linear',
    provider: 'Linear',
    description: 'Read and create Linear issues, projects, and cycles directly from your AI workflow.',
    tags: ['project', 'issues', 'linear'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@linear/mcp-server'],
      environment: { LINEAR_API_KEY: '{env:LINEAR_API_KEY}' },
      enabled: true,
    },
  },
  {
    name: 'jira',
    title: 'Jira',
    provider: 'Community',
    description: 'Query and manage Jira issues, sprints, and projects via the Jira REST API.',
    tags: ['project', 'issues', 'jira'],
    definition: {
      type: 'local',
      command: ['npx', '-y', 'mcp-jira'],
      environment: {
        JIRA_BASE_URL: '{env:JIRA_BASE_URL}',
        JIRA_EMAIL: '{env:JIRA_EMAIL}',
        JIRA_API_TOKEN: '{env:JIRA_API_TOKEN}',
      },
      enabled: true,
    },
  },

  // ── DATABASES ───────────────────────────────────────────────────────────
  {
    name: 'postgres',
    title: 'PostgreSQL',
    provider: 'Model Context Protocol',
    description: 'Database inspection and query workflows for PostgreSQL connection strings.',
    tags: ['database', 'postgres', 'official'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@modelcontextprotocol/server-postgres', '{env:POSTGRES_CONNECTION_STRING}'],
      enabled: true,
    },
  },
  {
    name: 'mysql-readonly',
    title: 'MySQL Readonly',
    provider: 'Community',
    description: 'Read-only MySQL MCP using env placeholders for safe credential handling.',
    tags: ['database', 'mysql', 'readonly'],
    definition: {
      type: 'local',
      command: ['npx', '-y', 'mysql-readonly-mcp'],
      environment: {
        MYSQL_HOST: '{env:MYSQL_HOST}',
        MYSQL_PORT: '{env:MYSQL_PORT}',
        MYSQL_USER: '{env:MYSQL_USER}',
        MYSQL_PASSWORD: '{env:MYSQL_PASSWORD}',
        MYSQL_DATABASE: '{env:MYSQL_DATABASE}',
      },
      enabled: true,
    },
  },
  {
    name: 'sqlite',
    title: 'SQLite',
    provider: 'Model Context Protocol',
    description: 'Query and explore local SQLite databases. Great for prototypes and embedded data stores.',
    tags: ['database', 'sqlite', 'local', 'official'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@modelcontextprotocol/server-sqlite', '--db-path', '{DB_PATH}'],
      enabled: true,
    },
    installNote: 'Replace {DB_PATH} with the path to your .sqlite file.',
  },
  {
    name: 'mongodb',
    title: 'MongoDB',
    provider: 'MongoDB',
    description: 'Query and inspect MongoDB collections, documents, and indexes with natural language.',
    tags: ['database', 'mongodb', 'nosql'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@mongodb-js/mongodb-mcp-server'],
      environment: { MONGODB_URI: '{env:MONGODB_URI}' },
      enabled: true,
    },
  },
  {
    name: 'redis',
    title: 'Redis',
    provider: 'Community',
    description: 'Read and write Redis keys, hashes, lists, and sets. Inspect TTLs and keyspaces.',
    tags: ['database', 'redis', 'cache'],
    definition: {
      type: 'local',
      command: ['npx', '-y', 'mcp-redis'],
      environment: { REDIS_URL: '{env:REDIS_URL}' },
      enabled: true,
    },
  },
  {
    name: 'supabase',
    title: 'Supabase',
    provider: 'Supabase',
    description: 'Manage Supabase projects: query tables, run SQL, inspect schema, and manage auth users.',
    tags: ['database', 'supabase', 'postgres'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@supabase/mcp-server-supabase@latest'],
      environment: {
        SUPABASE_URL: '{env:SUPABASE_URL}',
        SUPABASE_SERVICE_ROLE_KEY: '{env:SUPABASE_SERVICE_ROLE_KEY}',
      },
      enabled: true,
    },
  },
  {
    name: 'neon',
    title: 'Neon',
    provider: 'Neon',
    description: 'Serverless Postgres by Neon — manage branches, run queries, and inspect schemas.',
    tags: ['database', 'postgres', 'serverless'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@neondatabase/mcp-server-neon'],
      environment: { NEON_API_KEY: '{env:NEON_API_KEY}' },
      enabled: true,
    },
  },
  {
    name: 'turso',
    title: 'Turso',
    provider: 'Turso',
    description: 'Query and manage Turso (libSQL) databases at the edge. Inspect tables and run SQL.',
    tags: ['database', 'sqlite', 'edge'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@turso/mcp-server'],
      environment: {
        TURSO_DATABASE_URL: '{env:TURSO_DATABASE_URL}',
        TURSO_AUTH_TOKEN: '{env:TURSO_AUTH_TOKEN}',
      },
      enabled: true,
    },
  },
  {
    name: 'clickhouse',
    title: 'ClickHouse',
    provider: 'ClickHouse',
    description: 'Run analytical queries on ClickHouse data warehouse. Schema exploration and SQL execution.',
    tags: ['database', 'analytics', 'clickhouse'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@clickhouse/mcp-server'],
      environment: {
        CLICKHOUSE_HOST: '{env:CLICKHOUSE_HOST}',
        CLICKHOUSE_USER: '{env:CLICKHOUSE_USER}',
        CLICKHOUSE_PASSWORD: '{env:CLICKHOUSE_PASSWORD}',
      },
      enabled: true,
    },
  },

  // ── CLOUD & INFRASTRUCTURE ───────────────────────────────────────────────
  {
    name: 'aws-kb-retrieval',
    title: 'AWS Knowledge Base',
    provider: 'Model Context Protocol',
    description: 'Retrieve documents from Amazon Bedrock Knowledge Bases using semantic search.',
    tags: ['aws', 'rag', 'cloud', 'official'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@modelcontextprotocol/server-aws-kb-retrieval'],
      environment: {
        AWS_ACCESS_KEY_ID: '{env:AWS_ACCESS_KEY_ID}',
        AWS_SECRET_ACCESS_KEY: '{env:AWS_SECRET_ACCESS_KEY}',
        AWS_REGION: '{env:AWS_REGION}',
        KNOWLEDGE_BASE_ID: '{env:KNOWLEDGE_BASE_ID}',
      },
      enabled: true,
    },
  },
  {
    name: 'cloudflare',
    title: 'Cloudflare',
    provider: 'Cloudflare',
    description: 'Manage Cloudflare Workers, KV, D1, R2, and DNS records from your AI environment.',
    tags: ['cloud', 'cloudflare', 'edge'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@cloudflare/mcp-server-cloudflare'],
      environment: { CLOUDFLARE_API_TOKEN: '{env:CLOUDFLARE_API_TOKEN}' },
      enabled: true,
    },
  },
  {
    name: 'vercel',
    title: 'Vercel',
    provider: 'Community',
    description: 'Manage Vercel projects, deployments, domains, and environment variables via the Vercel API.',
    tags: ['cloud', 'vercel', 'deploy'],
    definition: {
      type: 'local',
      command: ['npx', '-y', 'mcp-vercel'],
      environment: { VERCEL_TOKEN: '{env:VERCEL_TOKEN}' },
      enabled: true,
    },
  },
  {
    name: 'kubernetes',
    title: 'Kubernetes',
    provider: 'Community',
    description: 'Inspect and manage Kubernetes clusters: pods, deployments, services, and logs.',
    tags: ['cloud', 'k8s', 'devops'],
    definition: {
      type: 'local',
      command: ['npx', '-y', 'mcp-k8s-go'],
      enabled: true,
    },
    installNote: 'Uses your local kubeconfig. Make sure kubectl is configured.',
  },
  {
    name: 'docker',
    title: 'Docker',
    provider: 'Docker',
    description: 'Manage Docker containers, images, volumes, and networks. Inspect logs and stats.',
    tags: ['devops', 'docker', 'containers'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@docker/mcp-server'],
      enabled: true,
    },
  },

  // ── BROWSER & AUTOMATION ────────────────────────────────────────────────
  {
    name: 'playwright',
    title: 'Playwright Browser',
    provider: 'Microsoft',
    description: 'Browser automation for screenshots, navigation, testing, and web workflows.',
    tags: ['browser', 'test', 'automation'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@playwright/mcp@latest'],
      enabled: true,
    },
  },
  {
    name: 'puppeteer',
    title: 'Puppeteer',
    provider: 'Model Context Protocol',
    description: 'Headless Chrome control via Puppeteer. Navigate, screenshot, fill forms, and extract content.',
    tags: ['browser', 'automation', 'official'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@modelcontextprotocol/server-puppeteer'],
      enabled: true,
    },
  },

  // ── FILESYSTEM & LOCAL TOOLS ─────────────────────────────────────────────
  {
    name: 'filesystem',
    title: 'Filesystem',
    provider: 'Model Context Protocol',
    description: 'Read/write files inside selected folders. Edit the allowed directory after installing.',
    tags: ['files', 'local', 'official'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@modelcontextprotocol/server-filesystem', '{PROJECT_PATH}'],
      enabled: true,
    },
    installNote: 'Replace {PROJECT_PATH} with the project folder you want to expose.',
  },
  {
    name: 'everything',
    title: 'Everything Search',
    provider: 'Model Context Protocol',
    description: 'Demo MCP server exposing all MCP primitives: tools, resources, and prompts. Good for testing.',
    tags: ['demo', 'test', 'official'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@modelcontextprotocol/server-everything'],
      enabled: true,
    },
  },

  // ── COMMUNICATION & PRODUCTIVITY ─────────────────────────────────────────
  {
    name: 'slack',
    title: 'Slack',
    provider: 'Model Context Protocol',
    description: 'Read channels, send messages, search conversations, and list users in your Slack workspace.',
    tags: ['communication', 'slack', 'official'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@modelcontextprotocol/server-slack'],
      environment: {
        SLACK_BOT_TOKEN: '{env:SLACK_BOT_TOKEN}',
        SLACK_TEAM_ID: '{env:SLACK_TEAM_ID}',
      },
      enabled: true,
    },
  },
  {
    name: 'google-drive',
    title: 'Google Drive',
    provider: 'Model Context Protocol',
    description: 'Search, read, and list files in Google Drive using OAuth credentials.',
    tags: ['storage', 'google', 'official'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@modelcontextprotocol/server-gdrive'],
      environment: {
        GOOGLE_CLIENT_ID: '{env:GOOGLE_CLIENT_ID}',
        GOOGLE_CLIENT_SECRET: '{env:GOOGLE_CLIENT_SECRET}',
      },
      enabled: true,
    },
  },
  {
    name: 'google-maps',
    title: 'Google Maps',
    provider: 'Model Context Protocol',
    description: 'Geocoding, directions, place search, and distance matrix via Google Maps API.',
    tags: ['maps', 'geo', 'official'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@modelcontextprotocol/server-google-maps'],
      environment: { GOOGLE_MAPS_API_KEY: '{env:GOOGLE_MAPS_API_KEY}' },
      enabled: true,
    },
  },
  {
    name: 'notion',
    title: 'Notion',
    provider: 'Notion',
    description: 'Read and write Notion pages, databases, and blocks. Search across your entire workspace.',
    tags: ['notes', 'notion', 'productivity'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@notionhq/notion-mcp-server'],
      environment: { NOTION_API_KEY: '{env:NOTION_API_KEY}' },
      enabled: true,
    },
  },
  {
    name: 'gmail',
    title: 'Gmail',
    provider: 'Community',
    description: 'Read, search, send, and label emails in Gmail via the Google API.',
    tags: ['email', 'google', 'communication'],
    definition: {
      type: 'local',
      command: ['npx', '-y', 'mcp-gmail'],
      environment: {
        GMAIL_CLIENT_ID: '{env:GMAIL_CLIENT_ID}',
        GMAIL_CLIENT_SECRET: '{env:GMAIL_CLIENT_SECRET}',
        GMAIL_REFRESH_TOKEN: '{env:GMAIL_REFRESH_TOKEN}',
      },
      enabled: true,
    },
  },
  {
    name: 'discord',
    title: 'Discord',
    provider: 'Community',
    description: 'Read channels, send messages, and manage a Discord bot from your AI workflow.',
    tags: ['communication', 'discord'],
    definition: {
      type: 'local',
      command: ['npx', '-y', 'discord-mcp'],
      environment: { DISCORD_TOKEN: '{env:DISCORD_TOKEN}' },
      enabled: true,
    },
  },
  {
    name: 'telegram',
    title: 'Telegram Bot',
    provider: 'Community',
    description: 'Send and receive Telegram messages through a bot token.',
    tags: ['communication', 'telegram'],
    definition: {
      type: 'local',
      command: ['npx', '-y', 'telegram-mcp'],
      environment: { TELEGRAM_BOT_TOKEN: '{env:TELEGRAM_BOT_TOKEN}' },
      enabled: true,
    },
  },

  // ── OBSERVABILITY & MONITORING ───────────────────────────────────────────
  {
    name: 'sentry',
    title: 'Sentry',
    provider: 'Sentry',
    description: 'Inspect Sentry issues, stack traces, events, and releases directly from your editor.',
    tags: ['monitoring', 'errors', 'sentry'],
    definition: {
      type: 'local',
      command: ['uvx', 'mcp-server-sentry'],
      environment: { SENTRY_AUTH_TOKEN: '{env:SENTRY_AUTH_TOKEN}' },
      enabled: true,
    },
    installNote: 'Requires Python and uv (https://docs.astral.sh/uv).',
  },
  {
    name: 'datadog',
    title: 'Datadog',
    provider: 'Datadog',
    description: 'Query Datadog metrics, logs, monitors, and dashboards from your AI workflow.',
    tags: ['monitoring', 'observability', 'datadog'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@datadog/mcp-server'],
      environment: {
        DD_API_KEY: '{env:DD_API_KEY}',
        DD_APP_KEY: '{env:DD_APP_KEY}',
        DD_SITE: '{env:DD_SITE}',
      },
      enabled: true,
    },
  },
  {
    name: 'grafana',
    title: 'Grafana',
    provider: 'Grafana',
    description: 'Query Grafana dashboards, alerts, and data sources. Search and visualize metrics.',
    tags: ['monitoring', 'grafana', 'metrics'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@grafana/mcp-grafana@latest'],
      environment: {
        GRAFANA_URL: '{env:GRAFANA_URL}',
        GRAFANA_API_KEY: '{env:GRAFANA_API_KEY}',
      },
      enabled: true,
    },
  },

  // ── AI & MEMORY ─────────────────────────────────────────────────────────
  {
    name: 'memory',
    title: 'Memory',
    provider: 'Model Context Protocol',
    description: 'Persistent key-value memory store. Lets AI agents remember facts across sessions.',
    tags: ['memory', 'local', 'official'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@modelcontextprotocol/server-memory'],
      enabled: true,
    },
  },
  {
    name: 'sequential-thinking',
    title: 'Sequential Thinking',
    provider: 'Model Context Protocol',
    description: 'Structured reasoning tool that guides models through multi-step problem solving.',
    tags: ['reasoning', 'local', 'official'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@modelcontextprotocol/server-sequential-thinking'],
      enabled: true,
    },
  },
  {
    name: 'openai',
    title: 'OpenAI',
    provider: 'OpenAI',
    description: 'Call OpenAI models, generate embeddings, and manage fine-tuning jobs via the OpenAI API.',
    tags: ['ai', 'openai', 'llm'],
    definition: {
      type: 'local',
      command: ['npx', '-y', 'openai-mcp'],
      environment: { OPENAI_API_KEY: '{env:OPENAI_API_KEY}' },
      enabled: true,
    },
  },

  // ── PAYMENTS & BUSINESS ──────────────────────────────────────────────────
  {
    name: 'stripe',
    title: 'Stripe',
    provider: 'Stripe',
    description: 'Manage Stripe customers, payments, subscriptions, and refunds from your AI workflow.',
    tags: ['payments', 'stripe', 'finance'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@stripe/mcp-server', '--tools=all'],
      environment: { STRIPE_SECRET_KEY: '{env:STRIPE_SECRET_KEY}' },
      enabled: true,
    },
  },
  {
    name: 'shopify',
    title: 'Shopify',
    provider: 'Shopify',
    description: 'Manage Shopify products, orders, customers, and inventory via the Admin API.',
    tags: ['ecommerce', 'shopify'],
    definition: {
      type: 'remote',
      url: 'https://mcp.shopify.com/mcp',
      environment: { SHOPIFY_ACCESS_TOKEN: '{env:SHOPIFY_ACCESS_TOKEN}' },
      enabled: true,
    },
  },

  // ── DEVELOPER TOOLS ──────────────────────────────────────────────────────
  {
    name: 'npm-search',
    title: 'npm Search',
    provider: 'Community',
    description: 'Search the npm registry, get package metadata, readme, and version info.',
    tags: ['npm', 'packages', 'search'],
    definition: {
      type: 'local',
      command: ['npx', '-y', 'mcp-npm-search'],
      enabled: true,
    },
  },
  {
    name: 'vscode-remote',
    title: 'VS Code Server',
    provider: 'Community',
    description: 'Interact with a remote VS Code Server instance: open files, run terminals, and manage extensions.',
    tags: ['vscode', 'editor', 'remote'],
    definition: {
      type: 'local',
      command: ['npx', '-y', 'vscode-mcp-server'],
      environment: { VSCODE_SERVER_URL: '{env:VSCODE_SERVER_URL}' },
      enabled: true,
    },
  },
  {
    name: 'figma',
    title: 'Figma',
    provider: 'Community',
    description: 'Inspect Figma files, frames, components, and styles. Extract design tokens and assets.',
    tags: ['design', 'figma', 'ui'],
    definition: {
      type: 'local',
      command: ['npx', '-y', 'figma-mcp'],
      environment: { FIGMA_ACCESS_TOKEN: '{env:FIGMA_ACCESS_TOKEN}' },
      enabled: true,
    },
  },
  {
    name: 'openapi-schema',
    title: 'OpenAPI / Swagger',
    provider: 'Community',
    description: 'Load any OpenAPI spec and expose its endpoints as callable MCP tools at runtime.',
    tags: ['api', 'openapi', 'rest'],
    definition: {
      type: 'local',
      command: ['npx', '-y', 'openapi-mcp-server'],
      environment: { OPENAPI_SPEC_URL: '{env:OPENAPI_SPEC_URL}' },
      enabled: true,
    },
    installNote: 'Set OPENAPI_SPEC_URL to a local file path or remote URL of your API spec.',
  },
  {
    name: 'nx',
    title: 'Nx Workspace',
    provider: 'Nx',
    description: 'Explore and run targets in an Nx monorepo: projects, tasks, dependencies, and cache.',
    tags: ['monorepo', 'nx', 'build'],
    definition: {
      type: 'local',
      command: ['npx', '-y', '@nx/mcp-server'],
      enabled: true,
    },
  },

  // ── FINANCE & DATA ───────────────────────────────────────────────────────
  {
    name: 'coinmarketcap',
    title: 'CoinMarketCap',
    provider: 'Community',
    description: 'Real-time cryptocurrency prices, market cap, volume, and trending coins.',
    tags: ['crypto', 'finance', 'data'],
    definition: {
      type: 'local',
      command: ['npx', '-y', 'coinmarketcap-mcp'],
      environment: { CMC_API_KEY: '{env:CMC_API_KEY}' },
      enabled: true,
    },
  },
  {
    name: 'alpha-vantage',
    title: 'Alpha Vantage',
    provider: 'Community',
    description: 'Stock quotes, forex rates, and technical indicators via the Alpha Vantage API.',
    tags: ['finance', 'stocks', 'data'],
    definition: {
      type: 'local',
      command: ['npx', '-y', 'alpha-vantage-mcp'],
      environment: { ALPHA_VANTAGE_API_KEY: '{env:ALPHA_VANTAGE_API_KEY}' },
      enabled: true,
    },
  },

  // ── IoT & SMART HOME ─────────────────────────────────────────────────────
  {
    name: 'home-assistant',
    title: 'Home Assistant',
    provider: 'Community',
    description: 'Control Home Assistant entities: lights, switches, sensors, automations, and scripts.',
    tags: ['iot', 'smart-home', 'hass'],
    definition: {
      type: 'local',
      command: ['npx', '-y', 'hass-mcp'],
      environment: {
        HASS_URL: '{env:HASS_URL}',
        HASS_TOKEN: '{env:HASS_TOKEN}',
      },
      enabled: true,
    },
  },
]
